USE [master]
GO
/****** Object:  Database [LATVIABANK]    Script Date: 19/04/2020 02:46:48 p. m. ******/
CREATE DATABASE [LATVIABANK]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LatviaBank', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LatviaBank.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LatviaBank_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LatviaBank_log.ldf' , SIZE = 2560KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LATVIABANK] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LATVIABANK].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LATVIABANK] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LATVIABANK] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LATVIABANK] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LATVIABANK] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LATVIABANK] SET ARITHABORT OFF 
GO
ALTER DATABASE [LATVIABANK] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LATVIABANK] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LATVIABANK] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LATVIABANK] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LATVIABANK] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LATVIABANK] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LATVIABANK] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LATVIABANK] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LATVIABANK] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LATVIABANK] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LATVIABANK] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LATVIABANK] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LATVIABANK] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LATVIABANK] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LATVIABANK] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LATVIABANK] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LATVIABANK] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LATVIABANK] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LATVIABANK] SET  MULTI_USER 
GO
ALTER DATABASE [LATVIABANK] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LATVIABANK] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LATVIABANK] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LATVIABANK] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [LATVIABANK] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'LATVIABANK', N'ON'
GO
ALTER DATABASE [LATVIABANK] SET QUERY_STORE = OFF
GO
USE [LATVIABANK]
GO
/****** Object:  Table [dbo].[CAT_CUENTAS]    Script Date: 19/04/2020 02:46:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAT_CUENTAS](
	[ID] [nvarchar](10) NOT NULL,
	[NOMBRE_CLIENTE] [nvarchar](50) NULL,
	[SALDO_ACTUAL] [numeric](18, 0) NULL,
 CONSTRAINT [PK_TBL_CUENTAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAT_LIBROS]    Script Date: 19/04/2020 02:46:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAT_LIBROS](
	[isbn] [int] NOT NULL,
	[nombre] [nvarchar](max) NOT NULL,
	[autor] [nvarchar](max) NOT NULL,
	[editorial] [nvarchar](max) NOT NULL,
	[unidades] [int] NOT NULL,
	[edicion] [int] NOT NULL,
	[escuela] [nvarchar](max) NOT NULL,
	[tematica] [nvarchar](max) NOT NULL,
	[asignatura] [nvarchar](max) NOT NULL,
 CONSTRAINT [pk_ISBN] PRIMARY KEY CLUSTERED 
(
	[isbn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAT_LIBROS_DAÑADOS]    Script Date: 19/04/2020 02:46:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAT_LIBROS_DAÑADOS](
	[isbn] [int] NOT NULL,
	[nombre] [nvarchar](max) NOT NULL,
	[autor] [nvarchar](max) NOT NULL,
	[editorial] [nvarchar](max) NOT NULL,
	[unidades] [int] NOT NULL,
	[edicion] [int] NOT NULL,
	[escuela] [nvarchar](max) NOT NULL,
	[tematica] [nvarchar](max) NOT NULL,
	[descripcion] [nvarchar](max) NOT NULL,
	[costo_reparacion] [int] NOT NULL,
	[asignatura] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[isbn] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAT_USERS]    Script Date: 19/04/2020 02:46:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAT_USERS](
	[ID_USER] [nvarchar](20) NOT NULL,
	[USERNAME] [nvarchar](20) NULL,
	[PASSWORD] [nvarchar](20) NULL,
	[STATUS] [nvarchar](20) NULL,
 CONSTRAINT [PK_TBL_Users] PRIMARY KEY CLUSTERED 
(
	[ID_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRA_CUENTAS]    Script Date: 19/04/2020 02:46:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRA_CUENTAS](
	[ID_CUENTA] [nvarchar](10) NOT NULL,
	[ID_MOVTO] [nvarchar](10) NOT NULL,
	[MONTO_MOVTO] [numeric](18, 0) NULL,
	[FECHA] [nvarchar](10) NULL,
	[HORA] [nvarchar](10) NULL,
 CONSTRAINT [PK_TBL_CUENTASMOVTOS] PRIMARY KEY CLUSTERED 
(
	[ID_CUENTA] ASC,
	[ID_MOVTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TRA_IMGS]    Script Date: 19/04/2020 02:46:48 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TRA_IMGS](
	[ID_DOC] [nvarchar](10) NOT NULL,
	[ID_FOTO] [nvarchar](10) NOT NULL,
	[IMAGEN] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_TBL_IMGS] PRIMARY KEY CLUSTERED 
(
	[ID_DOC] ASC,
	[ID_FOTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [LATVIABANK] SET  READ_WRITE 
GO
