//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_RECUPERAR
    {
        public int isbn { get; set; }
        public string nombre { get; set; }
        public int cedula { get; set; }
        public System.DateTime fechasoli { get; set; }
        public System.DateTime fechaentrega { get; set; }
    }
}
