//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_LIBROS
    {
        public int isbn { get; set; }
        public string nombre { get; set; }
        public string autor { get; set; }
        public string editorial { get; set; }
        public int unidades { get; set; }
        public int edicion { get; set; }
        public string escuela { get; set; }
        public string tematica { get; set; }
        public string asignatura { get; set; }
        public int cantidad { get; set; }
    }
}
