//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_LIBROS_DAÑADOS
    {
        public int isbn { get; set; }
        public string nombre { get; set; }
        public string autor { get; set; }
        public string editorial { get; set; }
        public int unidades { get; set; }
        public int edicion { get; set; }
        public string escuela { get; set; }
        public string tematica { get; set; }
        public string descripcion { get; set; }
        public int costo_reparacion { get; set; }
        public string asignatura { get; set; }
    }
}
