//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_CUENTAS
    {
        public string ID { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public Nullable<decimal> SALDO_ACTUAL { get; set; }
    }
}
