//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibrosContext : DbContext
    {
        public LibrosContext()
            : base("name=LibrosContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_CUENTAS> CAT_CUENTAS { get; set; }
        public virtual DbSet<CAT_LIBROS_DAÑADOS> CAT_LIBROS_DAÑADOS { get; set; }
        public virtual DbSet<CAT_USERS> CAT_USERS { get; set; }
        public virtual DbSet<TRA_CUENTAS> TRA_CUENTAS { get; set; }
        public virtual DbSet<TRA_IMGS> TRA_IMGS { get; set; }
        public virtual DbSet<CAT_LIBROS> CAT_LIBROS { get; set; }
    }
}
