//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_ASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRA_IMGS
    {
        public string ID_DOC { get; set; }
        public string ID_FOTO { get; set; }
        public byte[] IMAGEN { get; set; }
    }
}
